name: Winget

on:
  release:
    types: [released]

jobs:
  winget:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: CelikE.soko
          installers-regex: '_windows_(?:amd64|arm64)\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
